### ISSUE TITLE
how to start playing video in mute mode and with data connection.

### ISSUE THREAD

**Issue by toricameroon** [brucetoo/ListVideoPlay#1]
Hi,
Thanks for this mazing library.
I have a couple of issues.
1)How can  i start playing a video in mute Mode.
2) How can i play a video with a data connection and not wifi
Thanks

**Comment by brucetoo** [comment]
Question 1: I think [muteVideo](https://github.com/brucetoo/ListVideoPlay/blob/master/app/src/main/java/com/brucetoo/listvideoplay/videomanage/ui/VideoPlayerView.java#L511) will help you,(but i can not test yet.)

Question 2: I didn't handle not wifi state, so your video will be played in any network-scene.

**Comment by toricameroon** [comment]
Okay..Thanks. i will test it right away.Just that the app crashes when you try playing video with a data network

**Comment by brucetoo** [comment]
you can check the crash log and analysis..
