### ISSUE TITLE
Video Does not pause and resume onScroll 

### ISSUE THREAD

**Issue by Dharaa** [brucetoo/ListVideoPlay#13]
Video play pause on pause play button but can play pause on onScroll method. is there anyway ..?
 
Thank you....

**Comment by brucetoo** [comment]
i don't know what's your meaning..  the video can auto pause or resume in Fragment with new structure example named "LIST VIDEO PLAY SUPPORT".

**Comment by Dharaa** [comment]
Can video autoplay on scroll ? In that fragment ?

**Comment by brucetoo** [comment]
Yup, but the first time you need click a single video to play, then scroll listview to see the magic.(There are not logic to autoplay when you into that fragment, but you can add by yourself.)

**Comment by Dharaa** [comment]
Yes it is there but app crash on scroll it is not working properly.

**Comment by brucetoo** [comment]
Is latest version ?  can you paste the error log info here?

**Comment by Dharaa** [comment]
04-25 09:17:13.015 2046-2047/? E/ANDR-PERF-MPCTL: Invalid profile no. 0,
total profiles 0 only
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoSizeChanged
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoSizeChanged
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.048 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.049 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.049 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.064 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoPrepared
04-25 09:17:13.064 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoPrepared
04-25 09:17:13.085 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoStarted
04-25 09:17:13.085 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoStarted
04-25 09:17:13.107 2066-24857/? E/OMXNodeInstance:
setConfig(81237c8:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR:
Undefined(0x80001001)
04-25 09:17:13.107 4239-4239/com.brucetoo.listvideoplay
E/ListScrollDetector: onScrollStateChanged: itemView -> null edge ->
NONE_EDGE
04-25 09:17:13.107 4239-4239/com.brucetoo.listvideoplay
E/ListScrollDetector: onScrollStateChanged: itemView -> null edge ->
NONE_EDGE
04-25 09:17:13.110 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.110 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:13.111 2066-24856/? E/OMXNodeInstance:
setConfig(81237c8:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR:
Undefined(0x80001001)
04-25 09:17:13.279 2576-2597/? E/ActivityManager: ANR in
com.brucetoo.listvideoplay (com.brucetoo.listvideoplay/.MainActivity)
                                                  PID: 4239
                                                  Reason: Input dispatching
timed out (Waiting to send non-key event because the touched window has not
finished processing certain input events that were delivered to it over
500.0ms ago.  Wait queue length: 16.  Wait queue head age: 5764.9ms.)
                                                  Load: 6.83 / 6.12 / 6.03
                                                  CPU usage from 10341ms to
0ms ago (2018-04-25 09:17:00.001 to 2018-04-25 09:17:10.342):
                                                    5.3%
2576/system_server: 2.7% user + 2.6% kernel / faults: 267 minor
                                                    1.3%
4239/com.brucetoo.listvideoplay: 0.8% user + 0.4% kernel / faults: 200 minor
                                                    1.3%
25184/kworker/u17:5: 0% user + 1.3% kernel
                                                    1.2%
18116/kworker/u17:0: 0% user + 1.2% kernel
                                                    0.8%
3244/kworker/u16:3: 0% user + 0.8% kernel
                                                    0.3%
20596/kworker/u16:9: 0% user + 0.3% kernel
                                                    0.5% 434/
com.google.android.gm: 0.3% user + 0.1% kernel / faults: 82 minor
                                                    0.4% 269/spi4: 0% user
+ 0.4% kernel
                                                    0.4% 2069/mediaserver:
0.3% user + 0% kernel / faults: 93 minor
                                                    0.3%
578/surfaceflinger: 0.1% user + 0.1% kernel / faults: 1 minor
                                                    0.3%
12749/com.android.systemui: 0.2% user + 0% kernel / faults: 11 minor
                                                    0.2%
3471/com.android.phone: 0.1% user + 0% kernel
                                                    0.2% 31077/kworker/1:0:
0% user + 0.2% kernel
                                                    0% 3/ksoftirqd/0: 0%
user + 0% kernel
                                                    0.1% 15/ksoftirqd/1: 0%
user + 0.1% kernel
                                                    0.1% 29/ksoftirqd/3: 0%
user + 0.1% kernel
                                                    0.1% 331/mmc-cmdqd/0:
0% user + 0.1% kernel
                                                    0.1%
2068/media.extractor: 0% user + 0% kernel / faults: 87 minor
                                                    0.1%
2199/msm_irqbalance: 0% user + 0% kernel
                                                    0.1%
3856/irq/234-synapti: 0% user + 0.1% kernel
                                                    0.1%
6312/com.motorola.motocare: 0% user + 0% kernel / faults: 15 minor
                                                    0.1%
31255/kworker/u16:7: 0% user + 0.1% kernel
                                                    0% 7/rcu_preempt: 0%
user + 0% kernel
                                                    0% 10/rcuop/0: 0% user
+ 0% kernel
                                                    0% 22/ksoftirqd/2: 0%
user + 0% kernel
                                                    0% 25/rcuop/2: 0% user
+ 0% kernel
                                                    0% 32/rcuop/3: 0% user
+ 0% kernel
                                                    0% 96/system: 0% user +
0% kernel
                                                    0% 338/irq/35-spdm_bw_:
0% user + 0% kernel
                                                    0% 455/logd: 0% user +
0% kernel
                                                    0% 2046/perfd: 0% user
+ 0% kernel / faults: 7 minor
                                                    0% 2070/netd: 0% user +
0% kernel / faults: 51 minor
                                                    0% 2248/rild: 0% user +
0% kernel
                                                    0% 2547/kworker/3:0: 0%
user + 0% kernel
                                                    0%
3815/com.android.launcher3: 0% user + 0% kernel / faults: 42 minor
                                                    0% 4054/com.gaana: 0%
user + 0% kernel / faults: 1 minor
                                                    0% 4644/logcat: 0% user
+ 0% kernel
                                                    0%
20328/com.google.android.gms: 0% user + 0% kernel
                                                    0%
22361/net.one97.paytm: 0% user + 0% kernel
                                                    0% 23541/adbd: 0% user
+ 0% kernel / faults: 26 minor
                                                  2.8% TOTAL: 0.7% user +
0.9% kernel + 0% iowait + 0.5% irq + 0.5% softirq
                                                  CPU usage from 2156ms to
2684ms later (2018-04-25 09:17:12.498 to 2018-04-25 09:17:13.026):
                                                    14% 2576/system_server:
5.5% user + 9.2% kernel / faults: 2 minor
                                                      5.5%
2597/ActivityManager: 3.7% user + 1.8% kernel
                                                      5.5%
3131/InputDispatcher: 1.8% user + 3.7% kernel
                                                      1.8% 2598/android.ui:
1.8% user + 0% kernel
                                                      1.8%
3132/InputReader: 0% user + 1.8% kernel
                                                    14%
4239/com.brucetoo.listvideoplay: 11% user + 3.6% kernel / faults: 101 minor
                                                      7.3%
4239/o.listvideoplay: 7.3% user + 0% kernel
                                                      1.8% 4247/Jit thread
pool: 0% user + 1.8% kernel
                                                      1.8%
4439/Binder:4239_4: 1.8% user + 0% kernel
                                                      1.8%
4487/Binder:4239_5: 1.8% user + 0% kernel
                                                    3.3%
20596/kworker/u16:9: 0% user + 3.3% kernel
                                                    3.4% 23541/adbd: 1.7%
user + 1.7% kernel / faults: 40 minor
                                                      1.7% 23541/adbd: 1.7%
user + 0% kernel
                                                      1.7%
23543/->transport: 0% user + 1.7% kernel
                                                      1.7%
23544/<-transport: 1.7% user + 0% kernel
                                                    1.3% 326/cfinteractive:
0% user + 1.3% kernel
                                                    1.3% 455/logd: 0% user
+ 1.3% kernel
                                                      1.3% 464/logd.writer:
0% user + 1.3% kernel
                                                    1.4% 2046/perfd: 0%
user + 1.4% kernel / faults: 2 minor
                                                     +0% 4742/POSIX timer
202: 0% user + 0% kernel
                                                     +0% 4743/POSIX timer
202: 0% user + 0% kernel
                                                    1.4% 2069/mediaserver:
1.4% user + 0% kernel / faults: 16 minor
                                                      1.4%
17153/Binder:2069_7: 1.4% user + 0% kernel
                                                    1.6%
4650/com.google.android.gms.persistent: 1.6% user + 0% kernel / faults: 7
minor
                                                    1.6% 4729/logcat: 0%
user + 1.6% kernel
                                                    1.6%
04-25 09:17:13.320 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.324 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.339 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.342 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.358 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.362 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.373 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.375 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.388 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.391 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVisibleChange : edge -> BOTTOM_EDGE
04-25 09:17:13.393 4239-4239/com.brucetoo.listvideoplay E/ItemChecker:
getNextTrackerView Bottom: item = 3 rectLocal : Rect(0, 0 - 1028, 153)
04-25 09:17:13.393 4239-4239/com.brucetoo.listvideoplay E/ItemChecker:
getNextTrackerView Bottom: item = 2 rectLocal : Rect(0, 0 - 1028, 578)
04-25 09:17:13.393 4239-4239/com.brucetoo.listvideoplay
E/ListScrollDetector: onScrollStateChanged: itemView ->
com.brucetoo.videoplayer.videomanage.player.RatioImageView{c3320ac
V.ED..C.. ........ 0,0-1028,578 #7f0700c2 app:id/view_tracker} edge ->
BOTTOM_EDGE
04-25 09:17:13.400 4239-4239/com.brucetoo.listvideoplay E/ItemChecker:
getNextTrackerView Bottom: item = 3 rectLocal : Rect(0, 0 - 1028, 153)
04-25 09:17:13.401 4239-4239/com.brucetoo.listvideoplay E/ItemChecker:
getNextTrackerView Bottom: item = 2 rectLocal : Rect(0, 0 - 1028, 578)
04-25 09:17:13.401 4239-4239/com.brucetoo.listvideoplay
E/ListScrollDetector: onScrollStateChanged: itemView ->
com.brucetoo.videoplayer.videomanage.player.RatioImageView{c3320ac
V.ED..C.. ........ 0,0-1028,578 #7f0700c2 app:id/view_tracker} edge ->
BOTTOM_EDGE
04-25 09:17:13.438 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoStopped
04-25 09:17:13.438 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoStopped
04-25 09:17:17.750 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoSizeChanged
04-25 09:17:17.750 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoSizeChanged
04-25 09:17:17.750 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:17.750 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:18.752 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:18.752 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:19.754 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:19.754 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:19.771 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoPrepared
04-25 09:17:19.771 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoPrepared
04-25 09:17:19.786 2066-2222/? E/OMXNodeInstance:
setConfig(81237c9:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR:
Undefined(0x80001001)
04-25 09:17:19.789 2066-24856/? E/OMXNodeInstance:
setConfig(81237c9:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR:
Undefined(0x80001001)
04-25 09:17:19.798 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoStarted
04-25 09:17:19.798 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onVideoStarted
04-25 09:17:19.805 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:19.805 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:20.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:20.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:21.777 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:21.777 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:22.782 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:22.782 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:22.783 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:22.783 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:22.783 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:22.783 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:23.781 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:23.781 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:24.785 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:24.785 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:25.772 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:25.772 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:26.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:26.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:27.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:27.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:28.779 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:28.779 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:28.780 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:28.780 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:28.780 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:28.780 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onInfo
04-25 09:17:28.781 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:28.781 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:29.771 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:29.771 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:30.772 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:30.772 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:31.772 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:31.772 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:32.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:32.776 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:33.778 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:33.778 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:34.779 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:34.779 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:35.777 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:35.777 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:36.777 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:36.777 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:37.778 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:37.778 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:37.832 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:37.832 4239-4239/com.brucetoo.listvideoplay
E/ListSupportFragment: onBufferingUpdate
04-25 09:17:37.845 2046-2047/? E/ANDR-PERF-MPCTL: Invalid profile no. 0,
total profiles 0 only

**Comment by brucetoo** [comment]
Seems like ANR , but the app work fine in my phone.
