### ISSUE TITLE
How to implement Global Mute and Unmute 

### ISSUE THREAD

**Issue by ghost** [brucetoo/ListVideoPlay#14]
Hi,
How to implement global mute and unmute like face-book video player, once mute all video played with mute same unmute please help on this.

**Comment by brucetoo** [comment]
[IViewTracker#muteVideo](https://github.com/brucetoo/ListVideoPlay/blob/47ef9f10afe285301994dd37114d8131291c36b6/videoplayer/src/main/java/com/brucetoo/videoplayer/tracker/IViewTracker.java#L170) will help you
