### ISSUE TITLE
Https link not working

### ISSUE THREAD

**Issue by vkropivko** [brucetoo/ListVideoPlay#3]
Does the video work through https, plan to do support?

**Comment by brucetoo** [comment]
Https support it's work of MediaPlayer, you can custom [DefaultMediaPlayer](https://github.com/brucetoo/ListVideoPlay/blob/master/videoplayer/src/main/java/com/brucetoo/videoplayer/videomanage/player/DefaultMediaPlayer.java) use [ExoPlayer](https://github.com/google/ExoPlayer) or others MediaPlayer
