### ISSUE TITLE
Not Working as expected when App Paused

### ISSUE THREAD

**Issue by Venisosdks** [brucetoo/ListVideoPlay#7]
Video is still playing when App is in paused state in Android 7 Device.

**Comment by brucetoo** [comment]
you need auto pause playing video, i had not handle this logic in demo..

**Comment by Venisosdks** [comment]
Hi, Thanks For reply , I have one query .

Can i use this com.brucetoo.listvideoplay.videomanage.ui.VideoPlayerView view directly inside itemview instead of scrolling along with the listview/Recyclerview , are there any overhead?

**Comment by brucetoo** [comment]
it's ok in theory, but which could occupy more memory, and hard to manage~ so i suggest you do as i show in demo. As if do so, you can do many fluent animations, rotate device and the playing video not be interrupted and play again..
