### ISSUE TITLE
请问动画到详情页以后为什么视频会从头开始播放了，还有，为什么视频进入详情页以后没有了视频控制器

### ISSUE THREAD

**Issue by lingkongzhihe** [brucetoo/ListVideoPlay#8]
点击列表到顶部无缝播放，可是会从头开始播放，每次都从头开始，Demo上的详情也进去以后也没有了控制器，这个在哪里改啊

**Comment by brucetoo** [comment]
“会从头开始播放” 这个不会呀，无缝就是为了续播做的呀。  控制器的问题，自己仔细看下说明和代码吧。
